# Generated by Django 5.2 on 2025-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_date', models.DateField()),
                ('toll_hour', models.PositiveSmallIntegerField()),
                ('toll_10_minute_block', models.PositiveSmallIntegerField()),
                ('minute_of_hour', models.PositiveSmallIntegerField()),
                ('hour_of_day', models.PositiveSmallIntegerField()),
                ('day_of_week_int', models.PositiveSmallIntegerField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('toll_week', models.PositiveIntegerField()),
                ('time_period', models.CharField(max_length=50)),
                ('vehicle_class', models.CharField(max_length=50)),
                ('detection_group', models.CharField(max_length=50)),
                ('detection_region', models.CharField(max_length=50)),
                ('crz_entries', models.PositiveIntegerField()),
                ('excluded_roadway_entries', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vehicle Entries',
            },
        ),
    ]
